/**
 * Type definitions for WatchFace JSON structure
 * Matches the format generated by the frontend watch-assembly-tool
 */

export interface WatchFaceJSON {
  WatchName: string;
  WatchCode?: string;
  CornerX?: number | null;
  CornerY?: number | null;
  Width: number;
  Height: number;
  ThumbnailWidth: number;
  ThumbnailHeight: number;
  Corner: number;
  DeviceType?: string;
  CreateTime?: string;
  IsAlbum: boolean;
  ColorBit?: number;
  AlbumBackground?: any | null;
  FolderName: string;
  ImageData?: Record<string, any>; // Base64 encoded images
  WatchStyles: WatchStyle[];
}

export interface WatchStyle {
  StyleName: string;
  DragBindBases: DragBindComponent[];
  TemplateBinds: DragBindComponent[];
  ScreenType: number;
  Zh: {
    Width: number;
    Height: number;
    Item: MonitorItem;
    DragBindBases: any | null;
  };
}

export interface MonitorItem {
  KwhNum: number;
  StepNum: number;
  HeartRateNum: number;
  CalorieNum: number;
  CurrentDateTime: string;
  StrengthNum: number;
  IsOpen: boolean;
}

export interface DragBindComponent {
  $type: string;
  dragName: string;
  height: number;
  left: number;
  top: number;
  align: number;
  elementType: number | null;
  DragName: string;
  Width: number;
  DragId: string;
  Height: number;
  Left: number;
  Top: number;
  Align: number;
  ElementType: number | null;
  MaxNum: number;
  MinNum: number;
  SubItems: any[];
  Visable: boolean;
  ItemName: string;
  DefaultNum: number | null;
  VerifyNullNum: boolean;
  
  // Type-specific fields
  Source?: string; // DragBindImage, DragBindPoint
  ImageSource?: string[]; // DragBindNormalDateTime, DragBindNums, DragBindProgress
  ImageData?: string | string[]; // Base64 image data (single or array)
  DateTimeFormat?: string; // DragBindNormalDateTime
  UnitIcon?: string | null;
  SetDateTime?: string;
  LeadingZero?: boolean;
  CurrentNum?: number; // DragBindProgress, DragBindNums
  RatioNum?: number;
  TargetValue?: number;
  UnitSource?: string | null;
  FillType?: boolean; // DragBindProgress
  MinusSource?: string | null;
  EmptySource?: string | null; // DragBindNums (no data image)
  
  // DragBindPoint (analog clock hands)
  StartAngle?: number;
  EndAngle?: number;
  OriginPointX?: number;
  OriginPointY?: number;
  Value?: number;
  Angle?: number;
  ValueIndex?: number; // 0=hour, 1=minute, 2=second
}

/**
 * JieLi folder naming structure
 * Pattern: XXXX_类别#图层类型#元素名_显示标志_X坐标_Y坐标
 */
export interface JieLiFolderConfig {
  code: string; // e.g., "0101", "0201", "0601"
  category: string; // e.g., "主要", "电量", "时间"
  layerType: string; // "图片" (1), "文字" (2), "数字" (3)
  elementName: string; // e.g., "1背景", "电量进度条", "1(时)#4(十)"
  displayFlag: number; // 0 or 10
  x: number;
  y: number;
  images: string[]; // Array of image file paths or base64 data
}

/**
 * Component mapping to JieLi codes
 */
export enum JieLiComponentCode {
  // Main/Background (01XX)
  MAIN_BACKGROUND = '0101',
  MAIN_BLUETOOTH = '0102',
  
  // Battery (02XX)
  BATTERY_PROGRESS = '0201',
  BATTERY_TEXT = '0202',
  BATTERY_ICON = '0203',
  BATTERY_PERCENT = '0204',
  BATTERY_DIGIT_HUNDREDS = '0205',
  BATTERY_DIGIT_TENS = '0206',
  BATTERY_DIGIT_ONES = '0207',
  BATTERY_BG = '0208',
  BATTERY_IMG_SHORT = '0209',
  BATTERY_IMG_LONG = '0210',
  
  // General Date (03XX)
  DATE_MONTH_TENS = '0301',
  DATE_MONTH_ONES = '0302',
  DATE_SEPARATOR = '0303',
  DATE_DAY_TENS = '0304',
  DATE_DAY_ONES = '0305',
  DATE_YEAR_THOUSANDS = '0306',
  DATE_YEAR_HUNDREDS = '0307',
  DATE_YEAR_TENS = '0308',
  DATE_YEAR_ONES = '0309',
  
  // Chinese Date (04XX)
  CN_DATE_MONTH_TENS = '0401',
  CN_DATE_MONTH_ONES = '0402',
  CN_DATE_MONTH_TEXT = '0403',
  CN_DATE_DAY_TENS = '0404',
  CN_DATE_DAY_ONES = '0405',
  CN_DATE_DAY_TEXT = '0406',
  
  // Other Date (05XX)
  OTHER_WEEK = '0501',
  OTHER_AMPM = '0502',
  
  // Time (06XX)
  TIME_HOUR_TENS = '0601',
  TIME_HOUR_ONES = '0602',
  TIME_SEPARATOR1 = '0603',
  TIME_MINUTE_TENS = '0604',
  TIME_MINUTE_ONES = '0605',
  TIME_SEPARATOR2 = '0606',
  TIME_SECOND_TENS = '0607',
  TIME_SECOND_ONES = '0608',
  
  // Steps (07XX)
  STEPS_PROGRESS = '0701',
  STEPS_TEXT = '0702',
  STEPS_UNIT = '0703',
  STEPS_DIGIT_10K = '0705',
  STEPS_DIGIT_1K = '0706',
  STEPS_DIGIT_100 = '0707',
  STEPS_DIGIT_10 = '0708',
  STEPS_DIGIT_1 = '0709',
  STEPS_ICON = '0710',
  
  // Heart Rate (08XX)
  HEART_TEXT = '0801',
  HEART_UNIT = '0802',
  HEART_NO_DATA = '0803',
  HEART_DIGIT_100 = '0804',
  HEART_DIGIT_10 = '0805',
  HEART_DIGIT_1 = '0806',
  HEART_ICON = '0807',
  
  // Calories (09XX)
  CALORIE_PROGRESS = '0901',
  CALORIE_TEXT = '0902',
  CALORIE_UNIT = '0903',
  CALORIE_DIGIT_1K = '0905',
  CALORIE_DIGIT_100 = '0906',
  CALORIE_DIGIT_10 = '0907',
  CALORIE_DIGIT_1 = '0908',
  CALORIE_ICON = '0909',
  
  // Sleep (10XX)
  SLEEP_PROGRESS = '1001',
  SLEEP_UNIT = '1002',
  SLEEP_NO_DATA = '1003',
  SLEEP_DIGIT_100 = '1004',
  SLEEP_DIGIT_10 = '1005',
  SLEEP_DIGIT_1 = '1006',
  SLEEP_ICON = '1007',
  
  // Effects (11XX)
  EFFECT_1 = '1101',
  
  // Touch Areas (12XX)
  TOUCH_STEPS = '1201',
  TOUCH_HEART = '1202',
  TOUCH_CALORIE = '1203',
  TOUCH_SLEEP = '1204',
  TOUCH_XIAOAI = '1205',
  TOUCH_PAYMENT = '1206',
  
  // Pointers (13XX)
  POINTER_HOUR = '1301',
  POINTER_MINUTE = '1302',
  POINTER_SECOND = '1303',
  
  // Progress Bars (14XX-17XX)
  PROGRESS_BATTERY_BMP = '1401',
  PROGRESS_BATTERY_PNG = '1402',
  PROGRESS_BATTERY_DOT = '1403',
  PROGRESS_STEPS_BMP = '1501',
  PROGRESS_STEPS_PNG = '1502',
  PROGRESS_STEPS_DOT = '1503',
  PROGRESS_CALORIE_BMP = '1601',
  PROGRESS_CALORIE_PNG = '1602',
  PROGRESS_CALORIE_DOT = '1603',
  PROGRESS_SLEEP_BMP = '1701',
  PROGRESS_SLEEP_PNG = '1702',
  PROGRESS_SLEEP_DOT = '1703',
}

export interface ConversionResult {
  success: boolean;
  folderPath?: string;
  binFilePath?: string;
  error?: string;
  message?: string;
}
